// apps/web-solid/src/components/filters/Filters.tsx
import styles from "client-css/m/filters.module.scss";
// import { ListX, Search } from "lucide-solid";
import { For, Show } from "solid-js";
import { setTags, tags } from "../../utils/filters";
import TagInput from "../common/TagInput";
import { SortSelect } from "./SortSelect";
import { TagQuery } from "./TagQuery";

export const Filters = () => {
  const resetTags = (event: Event) => {
    event.preventDefault();
    setTags([]);
  };

  return (
    <div class={styles.main}>
      <Show when={tags().length}>
        <div class={styles["tag-container"]}>
          <For each={tags()}>
            {tag => (<TagQuery tag={tag} />)}
          </For>
          <div class={`${styles["tag-query"]} ${styles.reset}`}>
            <button onClick={resetTags}>
              {/* <ListX /> */}
              X
            </button>
          </div>
        </div>
      </Show>

      <TagInput
        // icon={Search}
        onSubmit={v => setTags(old => [...old, v])}
        onEscape={() => setTags([])}
      />

      <SortSelect />
    </div>
  );
};

// apps/web-tanstack-react/src/components/filters/Filters.tsx
import type { MouseEventHandler } from "react";
import { useFilters } from "#/stores/filters";
import styles from "client-css/m/filters.module.scss";
import { ListX, Search } from "lucide-react";
import { useCallback } from "react";
import TagInput from "../common/TagInput";
import { SortSelect } from "./SortSelect";
import { TagQuery } from "./TagQuery";

export const Filters = () => {
  const { tags, setTags } = useFilters();

  const resetTags: MouseEventHandler<HTMLButtonElement> = useCallback((event) => {
    event.preventDefault();
    setTags([]);
  }, [setTags]);

  return (
    <div className={styles.main}>
      {tags.length > 0 && (
        <div className={styles["tag-container"]}>
          {tags.map(tag => (<TagQuery key={tag} tag={tag} />))}
          <div className={`${styles["tag-query"]} ${styles.reset}`}>
            <button onClick={resetTags}>
              <ListX />
            </button>
          </div>
        </div>
      )}

      <TagInput
        icon={Search}
        onSubmit={value => setTags(prev => [...prev, value])}
        onEscape={() => setTags([])}
      />
      <SortSelect />
    </div>
  );
};
