// apps/web-solid/src/components/filters/TagQuery.tsx
import type { JSX } from "@solidjs/web/jsx-runtime";
import type { Component } from "solid-js";
import { createQuery } from "@urql/solid";
import styles from "client-css/m/filters.module.scss";
import { Tag } from "client-graphql/snippets";
// import { BadgeCheck, Pencil, X } from "lucide-solid";
import { createSignal, Show } from "solid-js";
import { setTags } from "../../utils/filters";
import { StatusBar } from "../status/StatusBar";
import TagDialog from "../tag/TagDialog";

export const TagQuery: Component<{ tag: string }> = (props) => {
  const [dialogOpen, setDialogOpen] = createSignal(false);

  const [result] = createQuery({
    query: Tag,
    variables: () => ({ slug: props.tag }),
  });

  const removeTag: JSX.EventHandlerUnion<HTMLButtonElement, Event> = (event) => {
    event.preventDefault();

    setTags(prev => prev.filter(t => t !== props.tag));
  };

  return (
    <>
      <div
        class={styles["tag-query"]}
        style:background-color={result.data?.tag.category?.color}
      >
        <span>{props.tag}</span>
        <Show when={result.data?.tag.approved}>
          {/* <BadgeCheck size={16} /> */}
          check
        </Show>
        <button
          onClick={(e) => {
            e.preventDefault();
            setDialogOpen(true);
          }}
          type="button"
        >
          {/* <Pencil /> */}
          edit
        </button>
        <button
          onClick={removeTag}
          type="button"
        >
          {/* <X /> */}
          X
        </button>
      </div>

      <TagDialog open={dialogOpen()} setOpen={setDialogOpen} slug={props.tag} />

      <StatusBar error={!!result.error} fetching={result.fetching} />
    </>
  );
};

// apps/web-tanstack-react/src/components/filters/TagQuery.tsx
import type { FC } from "react";
import { useFilters } from "#/stores/filters";
import styles from "client-css/m/filters.module.scss";
import { Tag } from "client-graphql/snippets";
import { BadgeCheck, Pencil, X } from "lucide-react";
import { useCallback, useState } from "react";
import { useQuery } from "urql";
import StatusBar from "../status/StatusBar";
import TagDialog from "../tag/TagDialog";

export const TagQuery: FC<{ tag: string }> = ({ tag }) => {
  const { setTags } = useFilters();

  const [dialogOpen, setDialogOpen] = useState(false);

  const [result] = useQuery({
    query: Tag,
    variables: { slug: tag },
  });

  const removeTag = useCallback(() => {
    setTags(prev => prev.filter(t => t !== tag));
  }, [setTags, tag]);

  return (
    <>
      <div
        className={styles["tag-query"]}
        style={{ backgroundColor: result.data?.tag.category?.color ?? undefined }}
      >
        <span>{tag}</span>
        {result.data?.tag.approved && <BadgeCheck size={16} />}
        <button
          onClick={(e) => {
            e.preventDefault();
            setDialogOpen(true);
          }}
          type="button"
        >
          <Pencil />
        </button>
        <button
          onClick={(e) => {
            e.preventDefault();
            removeTag();
          }}
          type="button"
        >
          <X />
        </button>
      </div>

      <TagDialog open={dialogOpen} setOpen={setDialogOpen} slug={tag} />

      <StatusBar error={!!result.error} fetching={result.fetching} />
    </>
  );
};
