// apps/web-nuxt/app/components/common/Checkbox.vue
<script setup lang="ts">
import styles from "client-css/m/checkbox.module.scss";

defineProps<{ label: string }>();
const model = defineModel<boolean>("checked");
</script>

<template>
  <label :class="styles.checkbox">
    <input
      type="checkbox"
      :checked="model"
      @input="e => model = (e.currentTarget as HTMLInputElement).checked"
    >
    <span :class="styles.checkmark" />
    <span>{{ label }}</span>
  </label>
</template>

// apps/web-svelte/src/lib/components/common/Checkbox.svelte
<script lang="ts">
  import styles from "client-css/m/checkbox.module.scss";

  let {
    checked = $bindable(),
    label,
  } = $props<{
    checked: boolean | undefined;
    label: string;
  }>();
</script>

<label class={styles.checkbox}>
  <input type="checkbox" bind:checked={checked} />
  <span class={styles.checkmark}></span>
  <span>{label}</span>
</label>
