// apps/web-tanstack-react/src/components/common/Select.tsx
import type { LucideIcon } from "lucide-react";
import type { FunctionComponent, InputEventHandler } from "react";
import styles from "client-css/m/select.module.scss";
import { useCallback } from "react";

const Select: FunctionComponent<{
  icon?: LucideIcon;
  options: (string | { value: string; label: string })[];
  value?: string;
  setValue?: (value: string) => void;
}> = ({ icon: Icon, options, value, setValue }) => {
  const handleInput = useCallback<InputEventHandler<HTMLSelectElement>>((event) => {
    event.preventDefault();

    setValue?.(event.currentTarget.value);
  }, [setValue]);

  return (
    <div className={styles.select}>
      {Icon && <Icon className={styles.icon} />}

      <select value={value} onInput={handleInput}>
        {options.map(option => (
          <option key={(typeof option === "string" ? option : option.value)} value={typeof option === "string" ? option : option.value}>{typeof option === "string" ? option : option.label}</option>
        ))}
      </select>
    </div>
  );
};

export default Select;

// apps/web-svelte/src/lib/components/common/Select.svelte
<script lang="ts">
  import { Icon as IconType } from "@lucide/svelte";
  import styles from "client-css/m/select.module.scss";

  let { icon, options, value = $bindable(), setValue }: {
    icon?: typeof IconType;
    options: (string | { value: string; label: string })[];
    value?: string;
    setValue?: (value?: string) => void;
  } = $props();

</script>

<div class={styles.select}>
  {#if icon}
    {@const Icon = icon}
    <Icon class={styles.icon} />
  {/if}

  <select
    oninput={(event) => {
      if (setValue) {
        event.preventDefault();
        setValue(event.currentTarget.value);
      }
    }}
    value={value}
  >
    {#each options as option (typeof option === "string" ? option : option.value)}
      <option value={typeof option === "string" ? option : option.value}>{typeof option === "string" ? option : option.label}</option>
    {/each}
  </select>
</div>
