// apps/web-solidstart/src/components/status/StatusBar.tsx
import type { Component } from "solid-js";
import styles from "client-css/m/status.module.scss";

export const StatusBar: Component<{
  error?: boolean;
  fetching?: boolean;
}> = (props) => {
  return (
    <div
      classList={{
        [styles.bar]: true,
        [styles.busy]: props.fetching,
        [styles.error]: props.error,
      }}
    />
  );
};

// apps/web-next/src/components/StatusBar.tsx
import styles from "client-css/m/status.module.scss";
import clsx from "clsx";

type StatusBarProps = {
  busy: boolean;
  error: boolean;
};

const StatusBar = ({ busy, error }: StatusBarProps) => (
  <div
    className={clsx(
      styles.bar,
      error && styles.error,
      busy && styles.busy,
    )}
  />
);

export default StatusBar;
