// apps/web-next/src/components/ScrollButtons.tsx
"use client";

import styles from "client-css/m/scrollbuttons.module.scss";
import clsx from "clsx";
import { ChevronDown, ChevronUp } from "lucide-react";
import { useEffect, useState } from "react";

const ScrollButtons = () => {
  const [showToTop, setShowToTop] = useState(false);
  const [showToBottom, setShowToBottom] = useState(false);

  const handleScroll = () => {
    setShowToTop(window.scrollY > 100);
    setShowToBottom(
      window.scrollY + window.innerHeight < document.body.scrollHeight - 100,
    );
  };

  useEffect(() => {
    window.addEventListener("scroll", handleScroll);
    return () => window.removeEventListener("scroll", handleScroll);
  }, []);

  return (
    <div className={styles.buttons}>
      <button
        className={clsx(!showToTop && styles.hidden)}
        onClick={() => window.scrollTo({ behavior: "smooth", top: 0 })}
        type="button"
      >
        <ChevronUp />
      </button>
      <button
        className={clsx(!showToBottom && styles.hidden)}
        onClick={() => {
          window.scrollTo({
            behavior: "smooth",
            top: globalThis.document.body.scrollHeight,
          });
        }}
        type="button"
      >
        <ChevronDown />
      </button>
    </div>
  );
};

export default ScrollButtons;

// apps/web-solidstart/src/components/ScrollButtons.tsx
import styles from "client-css/m/scrollbuttons.module.scss";
import { ChevronDown, ChevronUp } from "lucide-solid";
import { createEffect, createSignal } from "solid-js";

const ScrollButtons = () => {
  const [showToTop, setShowToTop] = createSignal();
  const [showToBottom, setShowToBottom] = createSignal();

  createEffect(() => {
    const onScroll = () => {
      setShowToTop(window.scrollY > 50);
      setShowToBottom(window.scrollY + window.innerHeight < globalThis.document.body.scrollHeight - 50);
    };

    window.addEventListener("scroll", onScroll);

    return () => {
      window.removeEventListener("scroll", onScroll);
    };
  });

  return (
    <div class={styles.buttons}>
      <button
        class={showToTop() ? undefined : styles.hidden}
        onClick={() => window.scrollTo({ behavior: "smooth", top: 0 })}
      >
        <ChevronUp />
      </button>
      <button
        class={showToBottom() ? undefined : styles.hidden}
        onClick={() => {
          window.scrollTo({
            behavior: "smooth",
            top: globalThis.document.body.scrollHeight,
          });
        }}
      >
        <ChevronDown />
      </button>
    </div>
  );
};

export default ScrollButtons;
