// apps/web-nuxt/app/components/TagChip.vue
<script setup lang="ts">
import styles from "client-css/m/imagepage.module.scss";
import { tagsStore } from "client-stores";
import { type TagExt } from "models";

const router = useRouter();

const props = defineProps<{
  tag: TagExt;
}>();

const onClick = () => {
  tagsStore.set([props.tag.slug]);
  void router.push("/");
};
</script>

<template>
  <button
    :class="styles['tag-chip']"
    :style="{ 'background-color': props.tag.category?.color ?? undefined }"
    @click="onClick"
  >
    {{ props.tag.slug }}
  </button>
</template>

// apps/web-solidstart/src/components/TagChip.tsx
import type { TagExt } from "models";
import type { Component } from "solid-js";
import { useNavigate } from "@solidjs/router";
import styles from "client-css/m/imagepage.module.scss";
import { tagsStore } from "client-stores";

const TagChip: Component<{ tag: TagExt }> = (props) => {
  const navigate = useNavigate();

  const onClick = () => {
    tagsStore.set([props.tag.slug]);
    navigate("/");
  };

  return (
    <button
      class={styles["tag-chip"]}
      onClick={onClick}
      style={props.tag.category?.color ? `background-color: ${props.tag.category?.color}` : undefined}
      type="button"
    >
      {props.tag.slug}
    </button>
  );
};

export default TagChip;
