// apps/web-solid/src/components/common/Button.tsx
import type { JSX } from "@solidjs/web/jsx-runtime";
// import type { LucideIcon } from "lucide-solid";
import type { Component } from "solid-js";
import styles from "client-css/m/button.module.scss";
import { children, omit } from "solid-js";

export type ButtonProps = {
  children?: JSX.Element;
  icon?: unknown;
} & JSX.ButtonHTMLAttributes<HTMLButtonElement>;

const Button: Component<ButtonProps> = (props) => {
  const restProps = omit(props, "class", "icon", "children");
  const safeChildren = children(() => props.children);

  return (
    <button class={`${styles.button} ${props.class}`} type="button" {...restProps}>
      {/* {props.icon && <Dynamic component={props.icon} />} */}
      {safeChildren()}
    </button>
  );
};

export default Button;

// apps/web-tanstack-react/src/components/common/Button.tsx
import type { LucideIcon } from "lucide-react";
import type { ButtonHTMLAttributes, FunctionComponent, ReactNode } from "react";
import styles from "client-css/m/button.module.scss";

export type ButtonProps = {
  children?: ReactNode;
  icon?: LucideIcon;
} & ButtonHTMLAttributes<HTMLButtonElement>;

const Button: FunctionComponent<ButtonProps> = ({ icon: Icon, className, children, ...restProps }) => {
  return (
    <button className={`${styles.button} ${className}`} type="button" {...restProps}>
      {Icon && <Icon />}
      {children}
    </button>
  );
};

export default Button;
