// apps/web-svelte/src/lib/components/common/Dialog.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import type { HTMLDialogAttributes } from "svelte/elements";
  import styles from "client-css/m/dialog.module.scss";

  let { children, open = $bindable(false), class: className, ...restProps }: { children: Snippet; open?: boolean } & HTMLDialogAttributes = $props();

  let dialogRef = $state<HTMLDialogElement>();

  $effect(() => {
    if (dialogRef) {
      if (open) {
        dialogRef.showModal();
      } else {
        dialogRef.close();
      }
    }
  });
</script>

{#if open}
  <dialog class={[className, styles.dialog]} bind:this={dialogRef} closedby="any" onclose={() => open = false} {...restProps}>
    {@render children?.()}
  </dialog>
{/if}

// apps/web-tanstack-react/src/components/common/Dialog.tsx
import type { DialogHTMLAttributes, FunctionComponent, ReactNode } from "react";
import styles from "client-css/m/dialog.module.scss";
import { useEffect, useRef, useState } from "react";

const Dialog: FunctionComponent<{
  children?: ReactNode;
  open?: boolean;
  setOpen?: (open: boolean) => void;
  className?: string;
} & DialogHTMLAttributes<HTMLDialogElement>> = ({ children, open: openExt, setOpen: setOpenExt, className, ...restProps }) => {
  const [open, setOpen] = useState(false);

  useEffect(() => {
    if (openExt) {
      // eslint-disable-next-line react/set-state-in-effect
      setOpen(openExt);
    }
  }, [openExt]);
  useEffect(() => {
    setOpenExt?.(open);
  }, [open, setOpenExt]);

  const dialogRef = useRef<HTMLDialogElement>(null);

  useEffect(() => {
    if (dialogRef.current) {
      if (open) {
        dialogRef.current.showModal();
      } else {
        dialogRef.current.close();
      }
    }
  }, [open]);

  if (!open) {
    return;
  }

  return (
    <dialog ref={dialogRef} className={`${className ?? ""} ${styles.dialog}`} closedby="any" onClose={() => setOpen(false)} {...restProps}>
      {children}
    </dialog>
  );
};

export default Dialog;
