// apps/web-svelte/src/lib/components/common/Input.svelte
<script lang="ts">
  import type { HTMLInputAttributes } from "svelte/elements";
  import styles from "client-css/m/input.module.scss";

  let { value = $bindable(""), ...restProps }: HTMLInputAttributes = $props();

</script>

<div class={styles.container}>
  <input type="text" bind:value={value} {...restProps} />
</div>

// apps/web-tanstack-react/src/components/common/Input.tsx
import type { FunctionComponent, InputHTMLAttributes } from "react";
import styles from "client-css/m/input.module.scss";

export type InputProps = {
  value: string;
  setValue: (value: string) => void;
} & InputHTMLAttributes<HTMLInputElement>;

const Input: FunctionComponent<InputProps> = ({ value, setValue, ...restProps }) => {
  return (
    <div className={styles.container}>
      <input
        type="text"
        value={value}
        onInput={event => setValue(event.currentTarget.value)}
        {...restProps}
      />
    </div>
  );
};

export default Input;
