// apps/web-tanstack-react/src/routes/login.tsx
import { createFileRoute } from "@tanstack/react-router";
import styles from "client-css/m/login.module.scss";

const Login = () => {
  const { returnTo } = Route.useLoaderData();
  const loginUrl = `/auth/login?returnTo=${encodeURIComponent(returnTo)}`;

  return (
    <main className={styles.page}>
      <div className={styles.eyebrow}>てる子 / Pixiv archive</div>
      <h1 className={styles.title}>A quieter way to browse.</h1>
      <p className={styles.intro}>Sign in with your organization account to continue to the illustration archive.</p>
      <section className={styles.card} aria-labelledby="signin-title">
        <h2 id="signin-title" className={styles.cardTitle}>Welcome back</h2>
        <p className={styles.cardText}>Your collection is waiting. Authentication is handled securely by your organization.</p>
        <a className={styles.button} href={loginUrl}>Continue with Authentik</a>
      </section>
    </main>
  );
};

export const Route = createFileRoute("/login")({
  loader: ({ location }) => ({ returnTo: new URLSearchParams(location.searchStr).get("returnTo") ?? "/" }),
  head: () => ({ meta: [{ title: "Sign in - てる子" }] }),
  component: Login,
});

// apps/web-svelte/src/routes/login/+page.svelte
<script lang="ts">
  import styles from "client-css/m/login.module.scss";

  type Props = { data: { returnTo: string } };
  const { data }: Props = $props();

  const loginUrl = $derived(`/auth/login?returnTo=${encodeURIComponent(data.returnTo)}`);
</script>

<svelte:head>
  <title>Sign in - てる子</title>
</svelte:head>

<main class={styles.page}>
  <div class={styles.eyebrow}>てる子 / Pixiv archive</div>
  <h1 class={styles.title}>A quieter way to browse.</h1>
  <p class={styles.intro}>Sign in with your organization account to continue to the illustration archive.</p>
  <section class={styles.card} aria-labelledby="signin-title">
    <h2 id="signin-title" class={styles.cardTitle}>Welcome back</h2>
    <p class={styles.cardText}>Your collection is waiting. Authentication is handled securely by your organization.</p>
    <a class={styles.button} href={loginUrl}>Continue with Authentik</a>
  </section>
</main>
