// apps/web-tanstack-react/src/components/gallery/Gallery.tsx
import type { ImageSort } from "models";
import type { FunctionComponent } from "react";
import styles from "client-css/m/gallery.module.scss";
import { useEffect, useRef } from "react";
import { useImages } from "#/hooks/useImages";
import ErrorMessage from "../status/ErrorMessage";
import StatusBar from "../status/StatusBar";
import ImageCard from "./ImageCard";

const Gallery: FunctionComponent<{
  tags: readonly string[];
  sort: ImageSort;
}> = ({ tags, sort }) => {
  const result = useImages(tags, sort);

  const endDivRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const observer = new IntersectionObserver((entries) => {
      if (entries[0] && entries[0].isIntersecting) {
        result.fetchMore();
      }
    });

    if (endDivRef.current) {
      observer.observe(endDivRef.current);
    }

    return () => {
      observer.disconnect();
    };
  }, [result]);

  return (
    <>
      {result.images && (
        <>
          <div className={styles.gallery}>
            {result.images.map(image => (
              <ImageCard key={image.id} image={image} />
            ))}
          </div>
          <div className={styles.sentinel} ref={endDivRef}></div>
        </>
      )}

      {result.error
        && <ErrorMessage error={result.error} title={result.error.name}></ErrorMessage>}

      <StatusBar error={!!result.error} fetching={result.fetching}></StatusBar>
    </>
  );
};

export default Gallery;

// apps/web-solidstart/src/components/gallery/Gallery.tsx
import type { ImageSort } from "models";
import type { Component } from "solid-js";
import styles from "client-css/m/gallery.module.scss";
import { For, onCleanup, onMount, Show } from "solid-js";
import { useImages } from "../../hooks/useImages";
import ErrorMessage from "../status/ErrorMessage";
import { StatusBar } from "../status/StatusBar";
import { ImageCard } from "./ImageCard";

const Gallery: Component<{
  tags: readonly string[];
  sort: ImageSort;
}> = (props) => {
  const { images, fetching, error, fetchMore } = useImages(() => props.tags, () => props.sort);

  let endDiv: HTMLDivElement | undefined;

  const observer = new IntersectionObserver((entries) => {
    if (entries[0] && entries[0].isIntersecting) {
      fetchMore();
    }
  });

  onMount(() => {
    observer.observe(endDiv!);
  });

  onCleanup(() => {
    observer.disconnect();
  });

  return (
    <>

      <div class={styles.gallery}>
        <For each={images()}>
          {image => (
            <ImageCard image={image} />
          )}
        </For>
      </div>

      <div class={styles.sentinel} ref={endDiv} />

      <Show when={error()}>
        <ErrorMessage error={error()} title={error()?.name} />
      </Show>

      <StatusBar error={!!error()} fetching={fetching()} />
    </>
  );
};

export default Gallery;
