// apps/web-tanstack-react/src/components/gallery/ImageCard.tsx
import type { ImageExt } from "models";
import type { FunctionComponent } from "react";
import { useFilters } from "#/stores/filters";
import { Link } from "@tanstack/react-router";
import styles from "client-css/m/gallery.module.scss";

const ImageCard: FunctionComponent<{ image: ImageExt }> = ({ image }) => {
  const { setTags } = useFilters();

  const onTagClick = (slug: string) => {
    setTags([slug]);
  };

  return (
    <div className={styles.card}>
      <Link to="/$id" params={{ id: image.id.toString() }}>
        <div className={styles["image-container"]}>
          <img
            alt={image.title ?? image.filename}
            height={image.height}
            src={`/img/${image.filename}`}
            width={image.width}
          />

          {!!image.title
            && (
              <div>
                {image.title}
              </div>
            )}
        </div>
      </Link>
      <div className={styles["tag-list"]}>
        {(image.tags ?? []).filter(tag => !tag.slug.startsWith("artist_")).map(tag => (
          <button
            key={tag.slug}
            onClick={() => onTagClick(tag.slug)}
            style={{ backgroundColor: tag.category?.color ?? "gray" }}
            type="button"
          >
            {tag.slug}
          </button>
        ))}
      </div>
    </div>

  );
};

export default ImageCard;

// apps/web-solidstart/src/components/gallery/ImageCard.tsx
import type { ImageExt } from "models";
import type { Component } from "solid-js";
import { A } from "@solidjs/router";
import styles from "client-css/m/gallery.module.scss";
import { For, Show } from "solid-js";
import { setTags } from "~/utils/filters";

export const ImageCard: Component<{ image: ImageExt }> = (props) => {
  const onTagClick = (slug: string) => {
    setTags([slug]);
  };

  return (
    <div class={styles.card}>
      <A href={`/${props.image.id}`}>
        <div class={styles["image-container"]}>
          <img
            alt={props.image.title ?? props.image.filename}
            height={props.image.height}
            src={`/img/${props.image.filename}`}
            width={props.image.width}
          />

          <Show when={!!props.image.title}>
            <div>{props.image.title}</div>
          </Show>
        </div>
      </A>
      <div class={styles["tag-list"]}>
        <For each={(props.image.tags ?? []).filter(tag => !tag.slug.startsWith("artist_"))}>
          {tag => (
            <button
              onClick={() => onTagClick(tag.slug)}
              style:background-color={tag.category?.color ?? "gray"}
              type="button"
            >
              {tag.slug}
            </button>
          )}
        </For>
      </div>
    </div>

  );
};
