// apps/web-svelte/src/lib/components/Nav.svelte
<script lang="ts">
  import styles from "client-css/m/nav.module.scss";
  import { Plus } from "lucide-svelte";
</script>

<div class={styles.bar}>
  <div class="container {styles.content}">
    <div class={styles.left}>
      <a class={styles.button} href="/">てる子</a>
    </div>
    <div>
      <a class="{styles.button} {styles.square}" href="/new">
        <Plus />
      </a>
    </div>
  </div>
</div>

// apps/web-tanstack-react/src/components/Nav.tsx
import styles from "client-css/m/nav.module.scss";
import { Plus } from "lucide-react";

const Nav = () => {
  return (
    <div className={styles.bar}>
      <div className={`container ${styles.content}`}>
        <div className={styles.left}>
          <a className={styles.button} href="/">てる子</a>
        </div>
        <div>
          <a className={`${styles.button} ${styles.square}`} href="/new">
            <Plus />
          </a>
        </div>
      </div>
    </div>
  );
};

export default Nav;
