// apps/web-solidstart/src/components/status/ErrorMessage.tsx
import type { Component } from "solid-js";
import { A } from "@solidjs/router";
import styles from "client-css/m/error.module.scss";
import { House } from "lucide-solid";
import { Show } from "solid-js";

const ErrorMessage: Component<{
  error?: Error;
  message?: string;
  subtitle?: string;
  title?: string;
}> = (props) => {
  return (
    <div class={styles.backdrop}>
      <div class="container">
        <div class={styles.above}>
          <A href="/">
            <House />
            <span>return home</span>
          </A>
        </div>
        <div class={styles.content}>
          <h1>{props.title || "An error occurred"}</h1>
          <Show when={props.subtitle || props.error}>
            <h2>{props.subtitle || props.error?.message}</h2>
          </Show>
          <Show when={props.message}>
            <span>{props.message}</span>
          </Show>
        </div>
      </div>
    </div>

  );
};

export default ErrorMessage;

// apps/web-tanstack-react/src/components/status/ErrorMessage.tsx
import type { FunctionComponent } from "react";
import { Link } from "@tanstack/react-router";
import styles from "client-css/m/error.module.scss";
import { House } from "lucide-react";

const ErrorMessage: FunctionComponent<{
  error?: Error;
  message?: string;
  subtitle?: string;
  title?: string;
}> = ({ error, message, subtitle, title }) => {
  return (

    <div className={styles.backdrop}>
      <div className="container">
        <div className={styles.above}>
          <Link to="/">
            <House />
            <span>return home</span>
          </Link>
        </div>
        <div className={styles.content}>
          <h1>{title || "An error occurred"}</h1>
          {(subtitle || error)
            && <h2>{subtitle || error?.message}</h2>}
          {!!message
            && <span>{message}</span>}
        </div>
      </div>
    </div>

  );
};

export default ErrorMessage;
