// apps/web-solidstart/src/components/status/StatusBar.tsx
import type { Component } from "solid-js";
import styles from "client-css/m/status.module.scss";

export const StatusBar: Component<{
  error?: boolean;
  fetching?: boolean;
}> = (props) => {
  return (
    <div
      classList={{
        [styles.bar]: true,
        [styles.busy]: props.fetching,
        [styles.error]: props.error,
      }}
    />
  );
};

// apps/web-tanstack-react/src/components/status/StatusBar.tsx
import type { FunctionComponent } from "react";
import styles from "client-css/m/status.module.scss";

const StatusBar: FunctionComponent<{ error?: boolean; fetching?: boolean }> = ({ fetching, error }) => {
  return (<div className={`${styles.bar}${fetching ? ` ${styles.busy}` : ""}${error ? ` ${styles.error}` : ""}`}></div>
  );
};

export default StatusBar;
