// apps/web-svelte/src/routes/+page.svelte
<script lang="ts">
  import Filters from "$lib/components/filters/Filters.svelte";
  import Gallery from "$lib/components/Gallery.svelte";
  import ScrollButtons from "$lib/components/ScrollButtons.svelte";
  import { filters } from "$lib/filters.svelte.js";
</script>

<svelte:head>
  <title>てる子</title>
</svelte:head>

<div class="container">
  <Filters />

  <Gallery sort={filters.sort} tags={filters.tags} />
</div>

<ScrollButtons />

// apps/web-tanstack-react/src/routes/index.tsx
import { Filters } from "#/components/filters/Filters";
import Gallery from "#/components/gallery/Gallery";
import ScrollButtons from "#/components/ScrollButtons";
import { useFilters } from "#/stores/filters";
import { createFileRoute } from "@tanstack/react-router";

const App = () => {
  const { tags, sort } = useFilters();
  return (
    <>
      <div className="container">
        <Filters />

        <Gallery tags={tags} sort={sort} />
      </div>
      <ScrollButtons />
    </>
  );
};

export const Route = createFileRoute("/")({ component: App });
