// apps/web-svelte/src/lib/components/filters/SortSelect.svelte
<script lang="ts">
  import { filters } from "$lib/filters.svelte.js";

  import { ArrowDownNarrowWide } from "@lucide/svelte";
  import { zImageSort } from "models";
  import Select from "../common/Select.svelte";

  const setValue = (value?: string) => {
    filters.sort = zImageSort.parse(value);
  };
</script>

<Select
  options={[{ value: "NEWEST", label: "newest" }, { value: "OLDEST", label: "oldest" }, { value: "RANDOM", label: "random" }]}
  icon={ArrowDownNarrowWide}
  bind:value={() => filters.sort, v => setValue(v)}
/>

// apps/web-solid/src/components/filters/SortSelect.tsx
// import { ArrowDownNarrowWide } from "lucide-solid";
import { setSort, sort } from "../../utils/filters";
import Select from "../common/Select";

export const SortSelect = () =>
  (
    <Select
      options={[{ value: "NEWEST", label: "newest" }, { value: "OLDEST", label: "oldest" }, { value: "RANDOM", label: "random" }]}
      // icon={ArrowDownNarrowWide}
      value={sort()}
      setValue={setSort}
    />
  );
