// apps/web-tanstack-react/src/components/common/Input.tsx
import type { FunctionComponent, InputHTMLAttributes } from "react";
import styles from "client-css/m/input.module.scss";

export type InputProps = {
  value: string;
  setValue: (value: string) => void;
} & InputHTMLAttributes<HTMLInputElement>;

const Input: FunctionComponent<InputProps> = ({ value, setValue, ...restProps }) => {
  return (
    <div className={styles.container}>
      <input
        type="text"
        value={value}
        onInput={event => setValue(event.currentTarget.value)}
        {...restProps}
      />
    </div>
  );
};

export default Input;

// apps/web-solid/src/components/common/Input.tsx
import type { Component, JSX } from "solid-js";
import styles from "client-css/m/input.module.scss";
import { splitProps } from "solid-js";

export type InputProps = {
  value: string;
  setValue: (value: string) => void;
} & JSX.InputHTMLAttributes<HTMLInputElement>;

const Input: Component<InputProps> = (props_) => {
  const [props, restProps] = splitProps(props_, ["value", "setValue"]);

  return (
    <div class={styles.container}>
      <input
        type="text"
        value={props.value}
        onInput={event => props.setValue(event.currentTarget.value)}
        {...restProps}
      />
    </div>
  );
};

export default Input;
