// apps/web-svelte/src/lib/components/tag/TagDialog.svelte
<script lang="ts">
  import { filters } from "$lib/filters.svelte";
  import styles from "client-css/m/tag.module.scss";
  import Dialog from "../common/Dialog.svelte";
  import TagEditSection from "./TagEditSection.svelte";

  let { open = $bindable(false), slug }: { open?: boolean; slug: string } = $props();

  const afterUpdate = (newSlug?: string) => {
    open = false;
    if (newSlug) {
      const idx = filters.tags.findIndex(el => el === slug);
      if (idx >= 0) {
        filters.tags = filters.tags.toSpliced(idx, 1, newSlug);
      }
    }
  };
</script>

<Dialog bind:open={open} class={styles["tag-dialog"]}>
  <TagEditSection {slug} afterUpdate={afterUpdate} />
</Dialog>

// apps/web-nuxt/app/components/tag/TagDialog.vue
<script setup lang="ts">
import styles from "client-css/m/tag.module.scss";
import Dialog from "../common/Dialog.vue";
import TagEditSection from "./TagEditSection.vue";

const props = defineProps<{ slug: string }>();
const open = defineModel("open", {
  default: false,
});

const { tags } = useFilters();

const afterUpdate = (newSlug?: string) => {
  open.value = false;
  if (newSlug) {
    const idx = tags.value.findIndex(el => el === props.slug);
    if (idx >= 0) {
      tags.value = tags.value.toSpliced(idx, 1, newSlug);
    }
  }
};
</script>

<template>
  <Dialog v-model:open="open" :class="styles['tag-dialog']">
    <TagEditSection :slug="slug" @after-update="afterUpdate" />
  </Dialog>
</template>
