// apps/web-tanstack-react/src/components/common/Button.tsx
import type { LucideIcon } from "lucide-react";
import type { ButtonHTMLAttributes, FunctionComponent, ReactNode } from "react";
import styles from "client-css/m/button.module.scss";

export type ButtonProps = {
  children?: ReactNode;
  icon?: LucideIcon;
} & ButtonHTMLAttributes<HTMLButtonElement>;

const Button: FunctionComponent<ButtonProps> = ({ icon: Icon, className, children, ...restProps }) => {
  return (
    <button className={`${styles.button} ${className}`} type="button" {...restProps}>
      {Icon && <Icon />}
      {children}
    </button>
  );
};

export default Button;

// apps/web-solidstart/src/components/common/Button.tsx
import type { LucideIcon } from "lucide-solid";
import type { Component, JSX } from "solid-js";
import styles from "client-css/m/button.module.scss";
import { children, splitProps } from "solid-js";
import { Dynamic } from "solid-js/web";

export type ButtonProps = {
  children?: JSX.Element;
  icon?: LucideIcon;
} & JSX.ButtonHTMLAttributes<HTMLButtonElement>;

const Button: Component<ButtonProps> = (props_) => {
  const [props, restProps] = splitProps(props_, ["class", "icon", "children"]);
  const safeChildren = children(() => props.children);

  return (
    <button class={`${styles.button} ${props.class}`} type="button" {...restProps}>
      {props.icon && <Dynamic component={props.icon} />}
      {safeChildren()}
    </button>
  );
};

export default Button;
