// apps/web-tanstack-react/src/components/common/Checkbox.tsx
import type { FunctionComponent } from "react";
import styles from "client-css/m/checkbox.module.scss";

const Checkbox: FunctionComponent<{
  checked: boolean;
  setChecked: (value: boolean) => void;
  label: string;
}> = ({ checked, setChecked, label }) => {
  return (
    <label className={styles.checkbox}>
      <input
        type="checkbox"
        checked={checked}
        onInput={e => setChecked(e.currentTarget.checked)}
      />
      <span className={styles.checkmark} />
      <span>{label}</span>
    </label>
  );
};

export default Checkbox;

// apps/web-solidstart/src/components/common/Checkbox.tsx
import type { Component } from "solid-js";
import styles from "client-css/m/checkbox.module.scss";

const Checkbox: Component<{
  checked: boolean;
  setChecked: (value: boolean) => void;
  label: string;
}> = (props) => {
  return (
    <label class={styles.checkbox}>
      <input
        type="checkbox"
        checked={props.checked}
        onInput={e => props.setChecked(e.currentTarget.checked)}
      />
      <span class={styles.checkmark} />
      <span>{props.label}</span>
    </label>
  );
};

export default Checkbox;
