// apps/web-tanstack-react/src/components/common/Dialog.tsx
import type { DialogHTMLAttributes, FunctionComponent, ReactNode } from "react";
import styles from "client-css/m/dialog.module.scss";
import { useEffect, useRef, useState } from "react";

const Dialog: FunctionComponent<{
  children?: ReactNode;
  open?: boolean;
  setOpen?: (open: boolean) => void;
  className?: string;
} & DialogHTMLAttributes<HTMLDialogElement>> = ({ children, open: openExt, setOpen: setOpenExt, className, ...restProps }) => {
  const [open, setOpen] = useState(false);

  useEffect(() => {
    if (openExt) {
      // eslint-disable-next-line react/set-state-in-effect
      setOpen(openExt);
    }
  }, [openExt]);
  useEffect(() => {
    setOpenExt?.(open);
  }, [open, setOpenExt]);

  const dialogRef = useRef<HTMLDialogElement>(null);

  useEffect(() => {
    if (dialogRef.current) {
      if (open) {
        dialogRef.current.showModal();
      } else {
        dialogRef.current.close();
      }
    }
  }, [open]);

  if (!open) {
    return;
  }

  return (
    <dialog ref={dialogRef} className={`${className ?? ""} ${styles.dialog}`} closedby="any" onClose={() => setOpen(false)} {...restProps}>
      {children}
    </dialog>
  );
};

export default Dialog;

// apps/web-solidstart/src/components/common/Dialog.tsx
import type { Component, JSX } from "solid-js";
import styles from "client-css/m/dialog.module.scss";
import { children, createComputed, createEffect, createSignal, Show, splitProps } from "solid-js";

const Dialog: Component<{
  children?: JSX.Element;
  open?: boolean;
  setOpen?: (value: boolean) => void;
} & JSX.DialogHtmlAttributes<HTMLDialogElement>> = (props_) => {
  const [props, restProps] = splitProps(props_, ["children", "open", "setOpen", "class"]);
  const safeChildren = children(() => props.children);

  const [open, setOpen] = createSignal(false);
  createComputed(() => {
    if (props.open != null) {
      setOpen(props.open);
    }
  });
  createComputed(() => {
    props.setOpen?.(open());
  });

  const [dialogRef, setDialogRef] = createSignal<HTMLDialogElement>();
  createEffect(() => {
    if (open()) {
      dialogRef()?.showModal();
    } else {
      dialogRef()?.close();
    }
  });

  return (
    <Show when={open}>
      <dialog class={`${props.class} ${styles.dialog}`} ref={setDialogRef} closedby="any" onClose={() => setOpen(false)} {...restProps}>
        {safeChildren()}
      </dialog>
    </Show>
  );
};

export default Dialog;
