// apps/web-nuxt/pages/[id].vue
<script setup lang="ts">
import type { ImageExt } from "models";

import { gql, useQuery } from "@urql/vue";
import { DownloadIcon } from "lucide-vue-next";

const route = useRoute();

const id = route.params.id as string;

const result = useQuery<{ image: ImageExt | null }>({
  query: gql`
    query Image($id: ID!) {
      image(id: $id) {
        id
        title
        source
        filename
        createdAt
        updatedAt
        tags {
          slug
          category {
            color
          }
        }
      }
    }
  `,
  variables: {
    id,
  },
});

const {
  data, fetching, stale, error,
} = result;

const fileExt = computed<string | null>(() => data.value?.image?.filename ? (data.value.image.filename.split(".").pop() ?? null) : null);

const scroll = (payload: Event) => {
  (payload.target as HTMLElement).scrollIntoView({
    behavior: "smooth",
    block: "center",
  });
};

useHead({
  title: computed(
    () =>
      `${data.value?.image?.title ? `${data.value.image.title} - ` : ""}てる子`,
  ),
});
</script>

<template>
  <div>
    <div
      class="space-y-1"
      v-if="data && data.image"
    >
      <img
        :src="`/img/${data.image.filename}`"
        @load="scroll"
        class="mx-auto max-h-screen"
      >

      <div class="container mx-auto pb-12">
        <div class="my-4 w-full p-1 lg:flex">
          <div class="overflow-hidden lg:flex-grow">
            <h1 class="text-3xl">
              {{ data.image.title }}
            </h1>

            <span class="text-sm">
              Source:
              <NuxtLink
                :href="data.image.source"
                class="link"
                target="_blank"
                v-if="data.image.source"
              >
                {{ data.image.source }}
              </NuxtLink>
              <span v-else>unknown</span>
            </span>
          </div>

          <div class="flex items-center lg:flex-shrink-0">
            <div
              class="my-1 flex-grow text-xs lg:mx-2 lg:text-right lg:text-sm"
            >
              <div>
                <span class="font-light">Created At: </span>
                {{ new Date(data.image.createdAt).toLocaleString() }}
              </div>
              <div>
                <span class="font-light">Updated At: </span>
                {{ new Date(data.image.updatedAt).toLocaleString() }}
              </div>
            </div>

            <NuxtLink
              :external="true"
              :href="`/${data.image.id}/original`"
              class="relative pb-2"
            >
              <DownloadIcon class="mx-1 h-10 w-10" />
              <span
                class="absolute bottom-0 left-0 right-0 mx-auto px-1 text-center text-[0.5rem] uppercase"
              >
                {{ fileExt }}
              </span>
            </NuxtLink>

            <NuxtLink
              :external="true"
              :href="`/${data.image.id}/avif`"
              class="relative pb-2"
              v-if="!!fileExt && fileExt !== 'avif'"
            >
              <DownloadIcon class="mx-1 h-10 w-10" />
              <span
                class="absolute bottom-0 left-0 right-0 mx-auto px-1 text-center text-[0.5rem] uppercase"
              >
                avif
              </span>
            </NuxtLink>

            <NuxtLink
              :external="true"
              :href="`/${data.image.id}/webp`"
              class="relative pb-2"
            >
              <DownloadIcon class="mx-1 h-10 w-10" />
              <span
                class="absolute bottom-0 left-0 right-0 mx-auto px-1 text-center text-[0.5rem] uppercase"
              >
                webp
              </span>
            </NuxtLink>
          </div>
        </div>

        <div class="w-full text-center lg:text-start">
          <TagChip
            :key="tag.slug"
            :tag="tag"
            v-for="tag in data.image.tags"
          />
        </div>
      </div>
    </div>

    <ErrorMessage
      :message="error.message"
      :title="error.name"
      v-if="error"
    />

    <ErrorMessage
      title="Not Found"
      v-if="!fetching && !error && (!data || !data.image)"
    />

    <StatusBar
      :error="!!error"
      :fetching="fetching || stale"
    />
  </div>
</template>

// apps/web-next/src/app/[id]/page.tsx
"use client";

import TagChip from "@/components/TagChip";
import { ImageExt } from "models";
import { DownloadIcon } from "lucide-react";
import Image from "next/image";
import { ReactElement, ReactEventHandler, useMemo } from "react";
import { gql, useQuery } from "urql";
import StatusBar from "@/components/StatusBar";
import ErrorMessage from "@/components/ErrorMessage";

const scroll: ReactEventHandler<HTMLImageElement> = (e) => {
  e.currentTarget.scrollIntoView({
    behavior: "smooth",
    block: "center",
  });
};

const ImagePage = ({ params }: { params: { id: string } }): ReactElement => {
  const { id } = params;

  const [result] = useQuery<{ image?: ImageExt }>({
    query: gql`
      query Image($id: ID!) {
        image(id: $id) {
          id
          title
          source
          filename
          createdAt
          updatedAt
          width
          height
          tags {
            slug
            category {
              color
            }
          }
        }
      }
    `,
    variables: { id },
  });

  const { data, fetching, stale, error } = result;

  const image = useMemo(() => data?.image, [data]);
  const fileExt = useMemo(() => image?.filename.split(".").pop(), [image]);

  return (
    <>
      {image && (
        <div className="space-y-1">
          <Image
            src={`/img/${image.filename}`}
            alt={image.title ?? image.filename}
            width={image.width}
            height={image.height}
            className="mx-auto max-h-screen object-contain"
            onLoad={scroll}
          />

          <div className="container mx-auto pb-12">
            <div className="my-4 w-full p-1 lg:flex">
              <div className="overflow-hidden lg:flex-grow">
                <h1 className="text-3xl">{image.title}</h1>

                <span className="text-sm">
                  Source:
                  <a
                    href={image.source || ""}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="link"
                  >
                    {image.source}
                  </a>
                </span>
              </div>

              <div className="flex items-center lg:flex-shrink-0">
                <div className="my-1 flex-grow text-xs lg:mx-2 lg:text-right lg:text-sm">
                  <div>
                    <span className="font-light">Created At: </span>
                    {image.createdAt.toLocaleString()}
                  </div>
                  <div>
                    <span className="font-light">Updated At: </span>
                    {image.updatedAt.toLocaleString()}
                  </div>
                </div>

                <a className="relative pb-2" href={`/${image.id}/original`}>
                  <DownloadIcon className="mx-1 h-10 w-10" />
                  <span className="absolute bottom-0 left-0 right-0 mx-auto px-1 text-center text-[0.5rem] uppercase">
                    {fileExt}
                  </span>
                </a>

                {!!fileExt && fileExt === "webp" && (
                  <a className="relative pb-2" href={`/${image.id}/avif`}>
                    <DownloadIcon className="mx-1 h-10 w-10" />
                    <span className="absolute bottom-0 left-0 right-0 mx-auto px-1 text-center text-[0.5rem] uppercase">
                      avif
                    </span>
                  </a>
                )}

                <a className="relative pb-2" href={`/${image.id}/webp`}>
                  <DownloadIcon className="mx-1 h-10 w-10" />
                  <span className="absolute bottom-0 left-0 right-0 mx-auto px-1 text-center text-[0.5rem] uppercase">
                    webp
                  </span>
                </a>
              </div>
            </div>

            <div className="w-full text-center lg:text-start">
              {(image.tags || []).map((tag) => (
                <TagChip key={tag.slug} tag={tag} />
              ))}
            </div>
          </div>
        </div>
      )}

      {error && <ErrorMessage title={error.name} error={error} />}

      {!fetching && !error && !image && <ErrorMessage title="Not Found" />}

      <StatusBar busy={fetching || stale} error={!!error} />
    </>
  );
};

export default ImagePage;
