// apps/web-next/src/components/Filters/SortSelect.tsx
import { useStore } from "@nanostores/react";
import { sortStore } from "client-common/stores";
import { ImageSort } from "models";

const SortSelect = () => {
  const sort = useStore(sortStore) ?? "NEWEST";

  const setSort = (sort: ImageSort) => {
    sortStore.set(sort);
  };

  return (
    <select
      className="h-10 w-24 rounded bg-base-100 px-2"
      onChange={(e) => setSort(e.target.value as ImageSort)}
      value={sort}
    >
      <option value="NEWEST">newest</option>
      <option value="OLDEST">oldest</option>
      <option value="RANDOM">random</option>
    </select>
  );
};

export default SortSelect;

// apps/web-nuxt/components/Filters/SortSelect.vue
<script setup lang="ts">
import { useStore } from "@nanostores/vue";
import { sortStore } from "client-common/stores";
import { type ImageSort } from "models";

const sort = useStore(sortStore);

const sortSel = ref<ImageSort>(sort.value || "NEWEST"); // TODO initial selection

const sortChange = () => {
  sortStore.set(sortSel.value);
};

watch(sort, () => {
  sortSel.value = sort.value || "NEWEST";
});
</script>

<template>
  <select
    @change="sortChange"
    class="h-10 w-24 rounded bg-base-100 px-2"
    v-model="sortSel"
  >
    <option value="NEWEST">
      newest
    </option>
    <option value="OLDEST">
      oldest
    </option>
    <option value="RANDOM">
      random
    </option>
  </select>
</template>
