// apps/web-next/src/components/Filters/TagQuery.tsx
import { X } from "lucide-react";
import { TagExt } from "models";
import { gql, useQuery } from "urql";
import StatusBar from "../StatusBar";
import { tagsStore } from "client-common/stores";
import { useStore } from "@nanostores/react";

type TagQueryProps = {
  slug: string;
};

const TagQuery = ({ slug }: TagQueryProps) => {
  const tags = useStore(tagsStore);

  const [{ data, fetching, stale, error }] = useQuery<{ tag: TagExt | null }>({
    query: gql`
      query Tag($slug: String!) {
        tag(slug: $slug) {
          category {
            color
          }
        }
      }
    `,
    variables: { slug },
  });

  const removeTag = () => {
    tagsStore.set(tags.filter((tag) => tag !== slug));
  };

  return (
    <>
      <div
        className="m-0.5 flex h-10 select-none items-center whitespace-nowrap rounded bg-gray-500 px-2 text-white"
        style={{
          backgroundColor: data?.tag?.category?.color ?? undefined,
        }}
      >
        <span className="mx-1">{slug}</span>
        <button
          className="mx-1 rounded transition hover:bg-black/20"
          onClick={removeTag}
        >
          <X />
        </button>
      </div>

      <StatusBar busy={fetching || stale} error={!!error} />
    </>
  );
};

export default TagQuery;

// apps/web-nuxt/components/Filters/TagQuery.vue
<script setup lang="ts">
import { gql, useQuery } from "@urql/vue";
import { X } from "lucide-vue-next";
import { TagExt } from "models";
import { useStore } from "@nanostores/vue";
import { tagsStore } from "client-common/stores";

const tags = useStore(tagsStore);

const props = defineProps<{
  tag: string;
}>();

const { data, fetching, stale, error } = useQuery<{ tag: TagExt }>({
  query: gql`
    query Tag($slug: String!) {
      tag(slug: $slug) {
        category {
          color
        }
      }
    }
  `,
  variables: { slug: props.tag },
});

const removeTag = () => {
  tagsStore.set(tags.value.filter((tag) => tag !== props.tag));
};
</script>

<template>
  <div
    class="m-0.5 flex h-10 select-none items-center whitespace-nowrap rounded bg-gray-500 px-2 text-white"
    :style="{
      backgroundColor: data?.tag?.category?.color ?? undefined,
    }"
  >
    <span class="mx-1">{{ props.tag }}</span>
    <button
      class="mx-1 rounded transition hover:bg-black/20"
      @click="removeTag"
    >
      <X />
    </button>
  </div>

  <StatusBar :fetching="fetching || stale" :error="!!error" />
</template>
