// apps/web-svelte/src/lib/components/Gallery.svelte
<script lang="ts">
  import type { ImageSort } from "models";
  import type { Action } from "svelte/action";
  import styles from "client-css/m/gallery.module.scss";
  import StatusBar from "#lib/components/status/StatusBar.svelte";
  import { useImages } from "#lib/images.svelte.js";
  import ImageCard from "./ImageCard.svelte";
  import ErrorMessage from "./status/ErrorMessage.svelte";

  type Props = {
    tags?: readonly string[];
    sort?: ImageSort;
  };

  const { tags = [], sort = "NEWEST" }: Props = $props();

  const result = useImages(() => tags, () => sort);

  const endAction: Action = (node) => {
    const observer = new IntersectionObserver((entries) => {
      if (entries[0] && entries[0].isIntersecting) {
        result.fetchMore();
      }
    });

    observer.observe(node);

    return {
      destroy() {
        observer.disconnect();
      },
    };
  };
</script>

{#if result.images}
  <div class={styles.gallery}>
    {#each result.images as image (image.id)}
      <ImageCard {image} />
    {/each}
  </div>
  <div class={styles.sentinel} use:endAction></div>
{/if}

{#if result.error}
  <ErrorMessage error={result.error} title={result.error.name}></ErrorMessage>
{/if}

<StatusBar error={!!result.error} fetching={result.fetching}></StatusBar>

// apps/web-tanstack-react/src/components/gallery/Gallery.tsx
import type { ImageSort } from "models";
import type { FunctionComponent } from "react";
import styles from "client-css/m/gallery.module.scss";
import { useEffect, useRef } from "react";
import { useImages } from "#/hooks/useImages";
import ErrorMessage from "../status/ErrorMessage";
import StatusBar from "../status/StatusBar";
import ImageCard from "./ImageCard";

const Gallery: FunctionComponent<{
  tags: readonly string[];
  sort: ImageSort;
}> = ({ tags, sort }) => {
  const result = useImages(tags, sort);

  const endDivRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const observer = new IntersectionObserver((entries) => {
      if (entries[0] && entries[0].isIntersecting) {
        result.fetchMore();
      }
    });

    if (endDivRef.current) {
      observer.observe(endDivRef.current);
    }

    return () => {
      observer.disconnect();
    };
  }, [result]);

  return (
    <>
      {result.images && (
        <>
          <div className={styles.gallery}>
            {result.images.map(image => (
              <ImageCard key={image.id} image={image} />
            ))}
          </div>
          <div className={styles.sentinel} ref={endDivRef}></div>
        </>
      )}

      {result.error
        && <ErrorMessage error={result.error} title={result.error.name}></ErrorMessage>}

      <StatusBar error={!!result.error} fetching={result.fetching}></StatusBar>
    </>
  );
};

export default Gallery;
