// apps/web-tanstack-react/src/components/filters/Filters.tsx
import type { MouseEventHandler } from "react";
import { useFilters } from "#/stores/filters";
import styles from "client-css/m/filters.module.scss";
import { ListX } from "lucide-react";
import { useCallback } from "react";
import { SortSelect } from "./SortSelect";
import { TagQuery } from "./TagQuery";
import { TagSearch } from "./TagSearch";

export const Filters = () => {
  const { tags, setTags } = useFilters();

  const resetTags: MouseEventHandler<HTMLButtonElement> = useCallback((event) => {
    event.preventDefault();
    setTags([]);
  }, [setTags]);

  return (
    <div className={styles.main}>
      {tags.length > 0 && (
        <div className={styles["tag-container"]}>
          {tags.map(tag => (<TagQuery key={tag} tag={tag} />))}
          <div className={`${styles["tag-query"]} ${styles.reset}`}>
            <button onClick={resetTags}>
              <ListX />
            </button>
          </div>
        </div>
      )}

      <TagSearch />
      <SortSelect />
    </div>
  );
};

// apps/web-svelte/src/lib/components/filters/Filters.svelte
<script lang="ts">
  import { filters } from "$lib/filters.svelte.js";
  import { ListX } from "@lucide/svelte";
  import styles from "client-css/m/filters.module.scss";
  import SortSelect from "./SortSelect.svelte";
  import TagQuery from "./TagQuery.svelte";
  import TagSearch from "./TagSearch.svelte";

  const resetTags = (event: Event) => {
    event.preventDefault();
    filters.tags = [];
  };
</script>

<div class={styles.main}>
  {#if filters.tags.length > 0}
    <div class={styles["tag-container"]}>
      {#each filters.tags as tag (tag)}
        <TagQuery {tag} />
      {/each}
      <div class={[styles["tag-query"], styles.reset]}>
        <button onclick={resetTags}>
          <ListX />
        </button>
      </div>
    </div>
  {/if}

  <TagSearch />

  <SortSelect />
</div>
