// apps/web-solidstart/src/components/filters/Filters.tsx
import styles from "client-css/m/filters.module.scss";
import { ListX } from "lucide-solid";
import { For, Show } from "solid-js";
import { setTags, tags } from "~/utils/filters";
import { SortSelect } from "./SortSelect";
import { TagQuery } from "./TagQuery";
import { TagSearch } from "./TagSearch";

export const Filters = () => {
  const resetTags = (event: Event) => {
    event.preventDefault();
    setTags([]);
  };

  return (
    <div class={styles.main}>
      <Show when={tags().length}>
        <div class={styles["tag-container"]}>
          <For each={tags()}>
            {tag => (<TagQuery tag={tag} />)}
          </For>
          <div class={`${styles["tag-query"]} ${styles.reset}`}>
            <button onClick={resetTags}>
              <ListX />
            </button>
          </div>
        </div>
      </Show>

      <TagSearch />

      <SortSelect />
    </div>
  );
};

// apps/web-svelte/src/lib/components/filters/Filters.svelte
<script lang="ts">
  import { filters } from "$lib/filters.svelte.js";
  import { ListX } from "@lucide/svelte";
  import styles from "client-css/m/filters.module.scss";
  import SortSelect from "./SortSelect.svelte";
  import TagQuery from "./TagQuery.svelte";
  import TagSearch from "./TagSearch.svelte";

  const resetTags = (event: Event) => {
    event.preventDefault();
    filters.tags = [];
  };
</script>

<div class={styles.main}>
  {#if filters.tags.length > 0}
    <div class={styles["tag-container"]}>
      {#each filters.tags as tag (tag)}
        <TagQuery {tag} />
      {/each}
      <div class={[styles["tag-query"], styles.reset]}>
        <button onclick={resetTags}>
          <ListX />
        </button>
      </div>
    </div>
  {/if}

  <TagSearch />

  <SortSelect />
</div>
