// apps/web-tanstack-react/src/components/filters/SortSelect.tsx
import type { InputEventHandler } from "react";
import { useFilters } from "#/stores/filters";
import styles from "client-css/m/filters.module.scss";
import { ArrowDownNarrowWide } from "lucide-react";
import { zImageSort } from "models";
import { useCallback } from "react";

export const SortSelect = () => {
  const { sort, setSort } = useFilters();

  const handleInput: InputEventHandler<HTMLSelectElement> = useCallback((event) => {
    event.preventDefault();

    setSort(zImageSort.parse(event.currentTarget.value));
  }, [setSort]);

  return (
    <div className={styles.sort}>
      <ArrowDownNarrowWide className={styles.icon} />

      <select
        onInput={handleInput}
        value={sort}
      >
        <option value="NEWEST">newest</option>
        <option value="OLDEST">oldest</option>
        <option value="RANDOM">random</option>
      </select>
    </div>
  );
};

// apps/web-svelte/src/lib/components/filters/SortSelect.svelte
<script lang="ts">
  import type { FormEventHandler } from "svelte/elements";

  import { ArrowDownNarrowWide } from "@lucide/svelte";

  import styles from "client-css/m/filters.module.scss";
  import { sortStore } from "client-stores";
  import { zImageSort } from "models";

  const handleInput: FormEventHandler<HTMLSelectElement> = (event) => {
    event.preventDefault();

    const parsedSort = zImageSort.parse(event.currentTarget.value);

    sortStore.set(parsedSort);
  };
</script>

<div class={styles.sort}>
  <ArrowDownNarrowWide class={styles.icon} />

  <select
    oninput={handleInput}
    value={$sortStore || "NEWEST"}
  >
    <option value="NEWEST">newest</option>
    <option value="OLDEST">oldest</option>
    <option value="RANDOM">random</option>
  </select>
</div>
