// apps/web-tanstack-react/src/components/common/Button.tsx
import type { LucideIcon } from "lucide-react";
import type { ButtonHTMLAttributes, FunctionComponent, ReactNode } from "react";
import styles from "client-css/m/button.module.scss";

export type ButtonProps = {
  children?: ReactNode;
  icon?: LucideIcon;
} & ButtonHTMLAttributes<HTMLButtonElement>;

const Button: FunctionComponent<ButtonProps> = ({ icon: Icon, className, children, ...restProps }) => {
  return (
    <button className={`${styles.button} ${className}`} type="button" {...restProps}>
      {Icon && <Icon />}
      {children}
    </button>
  );
};

export default Button;

// apps/web-nuxt/app/components/common/Button.vue
<script setup lang="ts">
import type { LucideIcon } from "@lucide/vue";
import styles from "client-css/m/button.module.scss";

defineProps<{
  icon?: LucideIcon;
}>();
</script>

<template>
  <button :class="styles.button" type="button">
    <component :is="icon" v-if="icon" />
    <slot />
  </button>
</template>
