// apps/web-svelte/src/lib/components/Dialog.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import styles from "client-css/m/dialog.module.scss";

  let { children, open = $bindable(false) }: { children: Snippet; open?: boolean } = $props();

  let dialogRef = $state<HTMLDialogElement>();

  $effect(() => {
    if (dialogRef) {
      if (open) {
        dialogRef.showModal();
      } else {
        dialogRef.close();
      }
    }
  });
</script>

{#if open}
  <dialog class={styles.dialog} bind:this={dialogRef} closedby="any" onclose={() => open = false}>
    {@render children?.()}
  </dialog>
{/if}

// apps/web-nuxt/app/components/common/Dialog.vue
<script setup lang="ts">
import styles from "client-css/m/dialog.module.scss";

const { class: className } = defineProps<{ class?: string }>();
const open = defineModel("open", {
  default: false,
});

const dialogRef = useTemplateRef("dialog");

watchEffect(() => {
  if (dialogRef.value) {
    if (open.value) {
      dialogRef.value.showModal();
    } else {
      dialogRef.value.close();
    }
  }
});
</script>

<template>
  <dialog v-if="open" ref="dialog" :class="`${className} ${styles.dialog}`" closedby="any" onclose="() => {open = false}">
    <slot />
  </dialog>
</template>
