// apps/web-svelte/src/lib/components/common/Select.svelte
<script lang="ts">
  import { Icon as IconType } from "@lucide/svelte";
  import styles from "client-css/m/select.module.scss";

  let { icon, options, value = $bindable() }: {
    icon?: typeof IconType;
    options: (string | { value: string; label: string })[];
    value?: string;
  } = $props();

</script>

<div class={styles.select}>
  {#if icon}
    {@const Icon = icon}
    <Icon class={styles.icon} />
  {/if}

  <select bind:value={value}>
    {#each options as option (typeof option === "string" ? option : option.value)}
      <option value={typeof option === "string" ? option : option.value}>{typeof option === "string" ? option : option.label}</option>
    {/each}
  </select>
</div>

// apps/web-nuxt/app/components/common/Select.vue
<script setup lang="ts">
import type { LucideIcon } from "@lucide/vue";
import styles from "client-css/m/select.module.scss";

defineProps<{
  icon?: LucideIcon;
  options: (string | { value: string; label: string })[];
}>();

const model = defineModel();
</script>

<template>
  <div :class="styles.select">
    <component :is="icon" v-if="icon" :class="styles.icon" />

    <select v-model="model">
      <option v-for="option in options" :key="(typeof option === 'string' ? option : option.value)" :value="typeof option === 'string' ? option : option.value">
        {{ typeof option === "string" ? option : option.label }}
      </option>
    </select>
  </div>
</template>
