// apps/web-nuxt/app/components/Filters/SortSelect.vue
<script setup lang="ts">
import type { ImageSort } from "models";
import { ArrowDownNarrowWide } from "@lucide/vue";
import { useStore } from "@nanostores/vue";
import styles from "client-css/m/filters.module.scss";
import { sortStore } from "client-stores";

const sort = useStore(sortStore);

const sortSel = ref<ImageSort>(sort.value || "NEWEST"); // TODO initial selection

const sortChange = () => {
  sortStore.set(sortSel.value);
};

watch(sort, () => {
  sortSel.value = sort.value || "NEWEST";
});
</script>

<template>
  <div :class="styles.sort">
    <ArrowDownNarrowWide :class="styles.icon" />

    <select
      v-model="sortSel"
      @change="sortChange"
    >
      <option value="NEWEST">
        newest
      </option>
      <option value="OLDEST">
        oldest
      </option>
      <option value="RANDOM">
        random
      </option>
    </select>
  </div>
</template>

// apps/web-next/src/components/Filters/SortSelect.tsx
import { useStore } from "@nanostores/react";
import styles from "client-css/m/filters.module.scss";
import { sortStore } from "client-stores";
import { ArrowDownNarrowWide } from "lucide-react";
import { ImageSort } from "models";

const SortSelect = () => {
  const sort = useStore(sortStore) ?? "NEWEST";

  const setSort = (sort: ImageSort) => {
    sortStore.set(sort);
  };

  return (
    <div className={styles.sort}>
      <ArrowDownNarrowWide className={styles.icon} />

      <select
        onChange={(e) => setSort(e.target.value as ImageSort)}
        value={sort}
      >
        <option value="NEWEST">newest</option>
        <option value="OLDEST">oldest</option>
        <option value="RANDOM">random</option>
      </select>
    </div>
  );
};

export default SortSelect;
