// apps/web-nuxt/app/components/Filters/TagSearch.vue
<script setup lang="ts">
import { useSuggestions } from "#imports";
import { Loader2, Search } from "@lucide/vue";
import { useStore } from "@nanostores/vue";
import styles from "client-css/m/filters.module.scss";

import { tagsStore } from "client-stores";

const tags = useStore(tagsStore);

const tagInput = ref("");
const activeSuggestion = ref(0);

const { fetching, suggestions } = useSuggestions(tagInput); // TODO handle error

const handleSubmit = () => {
  if (suggestions.value.length === 0) {
    return;
  }

  tagsStore.set([...tags.value, suggestions.value[activeSuggestion.value].slug]);
  tagInput.value = "";
  activeSuggestion.value = 0;
};

const handleKeyDown = (e: KeyboardEvent) => {
  switch (e.key) {
    case "ArrowDown": {
      e.preventDefault();
      activeSuggestion.value
        = (activeSuggestion.value + 1) % suggestions.value.length;

      break;
    }
    case "ArrowUp": {
      e.preventDefault();
      activeSuggestion.value
        = (activeSuggestion.value - 1 + suggestions.value.length)
          % suggestions.value.length;

      break;
    }
    case "Enter": {
      handleSubmit();

      break;
    }
    case "Escape": {
      tagInput.value = "";
      activeSuggestion.value = 0;
      tagsStore.set([]);

      break;
    }
    // No default
  }
};
</script>

<template>
  <div :class="styles['search-container']">
    <Search />

    <input
      v-model="tagInput"
      placeholder="Search..."
      type="text"
      @keydown="handleKeyDown"
    >
    <div
      v-if="fetching"
      :class="styles['suggestions-loading']"
    >
      <Loader2 :class="styles.icon" />
    </div>
    <ul
      v-if="suggestions.length > 0"
      :class="styles['suggestions-container']"
    >
      <li
        v-for="(suggestion, index) in suggestions"
        :key="suggestion.slug"
        :class="index === activeSuggestion && styles.active"
        :style="{
          'background-color':
            (index === activeSuggestion
              && suggestion.category
              && suggestion.category.color)
            || undefined,
          'color':
            (index !== activeSuggestion
              && suggestion.category
              && suggestion.category.color)
            || undefined,
        }"
        @click="handleSubmit"
        @mouseenter="activeSuggestion = index"
      >
        {{ suggestion.slug }}
      </li>
    </ul>
  </div>
</template>

// apps/web-next/src/components/Filters/TagSearch.tsx
import useSuggestions from "@/hooks/useSuggestions";
import { useStore } from "@nanostores/react";
import styles from "client-css/m/filters.module.scss";
import { tagsStore } from "client-stores";
import clsx from "clsx";
import { Loader2, Search } from "lucide-react";
import { useCallback, useState } from "react";

const TagInput = () => {
  const tags = useStore(tagsStore);

  const [tagInput, setTagInput] = useState("");
  const [activeSuggestion, setActiveSuggestion] = useState(0);

  const { fetching, suggestions } = useSuggestions(tagInput); // TODO handle error

  const handleSubmit = useCallback(
    (tagSlug: string) => {
      tagsStore.set([...tags, tagSlug]);

      setTagInput("");
      setActiveSuggestion(0);
    },
    [tags],
  );

  const handleKeyDown = useCallback(
    (e: React.KeyboardEvent<HTMLInputElement>) => {
      switch (e.key) {
        case "Enter": {
          e.preventDefault();

          const suggestion = suggestions[activeSuggestion];

          if (suggestion) {
            handleSubmit(suggestion.slug);
          }

          break;
        }
        case "ArrowUp": {
          e.preventDefault();

          if (activeSuggestion > 0) {
            setActiveSuggestion(activeSuggestion - 1);
          }

          break;
        }
        case "ArrowDown": {
          e.preventDefault();

          if (activeSuggestion < suggestions.length - 1) {
            setActiveSuggestion(activeSuggestion + 1);
          }

          break;
        }
        case "Escape": {
          e.preventDefault();

          setTagInput("");
          setActiveSuggestion(0);

          tagsStore.set([]);

          break;
        }
        // No default
      }
    },
    [activeSuggestion, handleSubmit, suggestions],
  );

  return (
    <div className={styles["search-container"]}>
      <Search />

      <input
        onChange={(e) => {
          setTagInput(e.target.value);
          setActiveSuggestion(0);
        }}
        onKeyDown={handleKeyDown}
        placeholder="Search..."
        type="text"
        value={tagInput}
      />
      {fetching && (
        <div className={styles["suggestions-loading"]}>
          <Loader2 className={styles.icon} />
        </div>
      )}
      {suggestions.length > 0 && (
        <ul className={styles["suggestions-container"]}>
          {suggestions.map((suggestion, index) => (
            <li
              className={clsx(index === activeSuggestion && styles.active)}
              key={suggestion.slug}
              onClick={() => handleSubmit(suggestion.slug)}
              onMouseEnter={() => setActiveSuggestion(index)}
              style={{
                backgroundColor:
                  (index === activeSuggestion &&
                    suggestion.category &&
                    suggestion.category.color) ||
                    undefined,
                color:
                  (index !== activeSuggestion &&
                    suggestion.category &&
                    suggestion.category.color) ||
                    undefined,
              }}
            >
              {suggestion.slug}
            </li>
          ))}
        </ul>
      )}
    </div>
  );
};

export default TagInput;
