// apps/web-svelte/src/lib/components/filters/Filters.svelte
<script lang="ts">
  import styles from "client-css/m/filters.module.scss";
  import { tagsStore } from "client-stores";
  import ListX from "lucide-svelte/icons/list-x";

  import SortSelect from "./SortSelect.svelte";
  import TagQuery from "./TagQuery.svelte";
  import TagSearch from "./TagSearch.svelte";

  const resetTags = () => {
    tagsStore.set([]);
  };
</script>

<div class={styles.main}>
  {#if $tagsStore.length > 0}
    <div class={styles["tag-container"]}>
      {#each $tagsStore as tag}
        {#key tag}
          <TagQuery {tag} />
        {/key}
      {/each}
      <div class={[styles["tag-query"], styles.reset]}>
        <button on:click|preventDefault={resetTags}>
          <ListX />
        </button>
      </div>
    </div>
  {/if}

  <TagSearch />

  <SortSelect />
</div>

// apps/web-nuxt/app/components/Filters/index.vue
<!-- eslint-disable vue/multi-word-component-names -->
<script setup lang="ts">
import { ListX } from "@lucide/vue";
import { useStore } from "@nanostores/vue";
import styles from "client-css/m/filters.module.scss";
import { tagsStore } from "client-stores";

import SortSelect from "./SortSelect.vue";
import TagQuery from "./TagQuery.vue";
import TagSearch from "./TagSearch.vue";

const tags = useStore(tagsStore);
</script>

<template>
  <div :class="styles.main">
    <div
      v-if="tags.length > 0"
      :class="styles['tag-container']"
    >
      <TagQuery
        v-for="tag in tags"
        :key="tag"
        :tag="tag"
      />
      <div :class="[styles['tag-query'], styles.reset]">
        <button @click="() => tagsStore.set([])">
          <ListX />
        </button>
      </div>
    </div>

    <TagSearch />

    <SortSelect />
  </div>
</template>
