// apps/web-next/src/components/Filters/index.tsx
"use client";

import { useStore } from "@nanostores/react";
import styles from "client-css/m/filters.module.scss";
import { tagsStore } from "client-stores";

import SortSelect from "./SortSelect";
import TagQuery from "./TagQuery";
import TagSearch from "./TagSearch";

const Filters = () => {
  const tags = useStore(tagsStore);

  return (
    <div className={styles.main}>
      {tags.length > 0 && (
        <div className={styles["tag-container"]}>
          {tags.map((tag) => (
            <TagQuery key={tag} slug={tag} />
          ))}
        </div>
      )}

      <TagSearch />

      <SortSelect />
    </div>
  );
};

export default Filters;

// apps/web-nuxt/app/components/Filters/index.vue
<!-- eslint-disable vue/multi-word-component-names -->
<script setup lang="ts">
import { ListX } from "@lucide/vue";
import { useStore } from "@nanostores/vue";
import styles from "client-css/m/filters.module.scss";
import { tagsStore } from "client-stores";

import SortSelect from "./SortSelect.vue";
import TagQuery from "./TagQuery.vue";
import TagSearch from "./TagSearch.vue";

const tags = useStore(tagsStore);
</script>

<template>
  <div :class="styles.main">
    <div
      v-if="tags.length > 0"
      :class="styles['tag-container']"
    >
      <TagQuery
        v-for="tag in tags"
        :key="tag"
        :tag="tag"
      />
      <div :class="[styles['tag-query'], styles.reset]">
        <button @click="() => tagsStore.set([])">
          <ListX />
        </button>
      </div>
    </div>

    <TagSearch />

    <SortSelect />
  </div>
</template>
