// apps/web-tanstack-react/src/components/filters/TagQuery.tsx
import type { FC } from "react";
import { useFilters } from "#/stores/filters";
import styles from "client-css/m/filters.module.scss";
import { Tag } from "client-graphql/snippets";
import { BadgeCheck, Pencil, X } from "lucide-react";
import { useCallback, useState } from "react";
import { useQuery } from "urql";
import StatusBar from "../status/StatusBar";
import TagDialog from "../tag/TagDialog";

export const TagQuery: FC<{ tag: string }> = ({ tag }) => {
  const { setTags } = useFilters();

  const [dialogOpen, setDialogOpen] = useState(false);

  const [result] = useQuery({
    query: Tag,
    variables: { slug: tag },
  });

  const removeTag = useCallback(() => {
    setTags(prev => prev.filter(t => t !== tag));
  }, [setTags, tag]);

  return (
    <>
      <div
        className={styles["tag-query"]}
        style={{ backgroundColor: result.data?.tag.category?.color ?? undefined }}
      >
        <span>{tag}</span>
        {result.data?.tag.approved && <BadgeCheck size={16} />}
        <button
          onClick={(e) => {
            e.preventDefault();
            setDialogOpen(true);
          }}
          type="button"
        >
          <Pencil />
        </button>
        <button
          onClick={(e) => {
            e.preventDefault();
            removeTag();
          }}
          type="button"
        >
          <X />
        </button>
      </div>

      <TagDialog open={dialogOpen} setOpen={setDialogOpen} slug={tag} />

      <StatusBar error={!!result.error} fetching={result.fetching} />
    </>
  );
};

// apps/web-nuxt/app/components/Filters/TagQuery.vue
<script setup lang="ts">
import { BadgeCheck, Pencil, X } from "@lucide/vue";
import { useQuery } from "@urql/vue";
import styles from "client-css/m/filters.module.scss";
import { Tag } from "client-graphql/snippets";

const props = defineProps<{
  tag: string;
}>();

const { tags } = useFilters();

const dialogOpen = ref(false);

const {
  data,
  fetching,
  stale,
  error,
} = useQuery({
  query: Tag,
  variables: { slug: props.tag },
});

const removeTag = () => {
  tags.value = tags.value.filter(tag => tag !== props.tag);
};
</script>

<template>
  <div
    :class="styles['tag-query']"
    :style="{
      backgroundColor: data?.tag?.category?.color ?? undefined,
    }"
  >
    <span>{{ props.tag }}</span>
    <BadgeCheck v-if="data?.tag.approved" :size="16" />
    <button
      type="button"
      @click="dialogOpen = true"
    >
      <Pencil />
    </button>
    <button
      type="button"
      @click="removeTag"
    >
      <X />
    </button>
  </div>

  <TagDialog v-model:open=" dialogOpen " :slug="tag" />

  <StatusBar
    :error="!!error"
    :fetching="fetching || stale"
  />
</template>
