// apps/web-nuxt/app/components/ImageCard.vue
<script setup lang="ts">
import type { ImageExt } from "models";
import styles from "client-css/m/gallery.module.scss";
import { tagsStore } from "client-stores";

const props = defineProps<{
  image: ImageExt;
}>();
</script>

<template>
  <div
    :class="styles.card"
  >
    <NuxtLink :href="`/${props.image.id}`">
      <div :class="styles['image-container']">
        <img
          :height="props.image.height"
          :src="`/img/${props.image.filename}`"
          :width="props.image.width"
        >

        <div
          v-if="!!props.image.title"
        >
          {{ props.image.title }}
        </div>
      </div>
    </NuxtLink>
    <div
      :class="styles['tag-list']"
    >
      <template
        v-for="tag in props.image.tags?.filter(
          (tag) => !tag.slug.startsWith('artist_'),
        )"
        :key="tag.slug"
      >
        <button
          :style="{ backgroundColor: tag.category?.color ?? 'gray' }"
          type="button"
          @click="() => tagsStore.set([tag.slug])"
        >
          {{ tag.slug }}
        </button>
      </template>
    </div>
  </div>
</template>

// apps/web-svelte/src/lib/components/ImageCard.svelte
<script lang="ts">
  import type { ImageExt } from "models";

  import styles from "client-css/m/gallery.module.scss";
  import { tagsStore } from "client-stores";
  import { fly } from "svelte/transition";

  type Props = {
    image: ImageExt;
  };

  const { image }: Props = $props();

  const onTagClick = (slug: string) => {
    tagsStore.set([slug]);
  };
</script>

<div class={styles.card} in:fly={{ y: 200 }}>
  <a href={`/${image.id}`}>
    <div class={styles["image-container"]}>
      <img
        alt={image.title ?? image.filename}
        height={image.height}
        src={`/img/${image.filename}`}
        width={image.width}
      />

      {#if !!image.title}
        <div>
          {image.title}
        </div>
      {/if}
    </div>
  </a>
  <div class={styles["tag-list"]}
  >
    {#each (image.tags ?? []).filter((tag) => !tag.slug.startsWith("artist_")) as tag}
      <button
        onclick={() => onTagClick(tag.slug)}
        style:background-color={tag.category?.color ?? "gray"}
        type="button"
      >
        {tag.slug}
      </button>
    {/each}
  </div>
</div>
