// apps/web-nuxt/components/ErrorMessage.vue
<script setup lang="ts">
import { Home } from "lucide-vue-next";

const props = defineProps<{
  title?: string;
  subtitle?: string;
  message?: string;
  error?: Error;
}>();
</script>

<template>
  <div class="fixed inset-0 z-50 flex items-center justify-center bg-black/50">
    <div class="container">
      <div class="my-3 px-8 text-white">
        <a class="flex flex-row items-center space-x-1" href="/">
          <Home />
          <span>return home</span>
        </a>
      </div>
      <div
        class="rounded border-4 border-error bg-neutral p-8 text-neutral-content"
      >
        <h1 class="mb-2 text-5xl">{{ title || "An error occurred" }}</h1>
        <h2 v-if="subtitle || error" class="my-2 text-3xl">
          {{ subtitle || error?.message }}
        </h2>
        <span v-if="message">{{ message }}</span>
      </div>
    </div>
  </div>
</template>

// apps/web-svelte/src/lib/components/status/ErrorMessage.svelte
<script lang="ts">
  import { Home } from "lucide-svelte";

  export let title: string | undefined = "An error occurred";
  export let subtitle: string | undefined = undefined;
  export let message: string | undefined = undefined;
  export let error: Error | undefined = undefined;
</script>

<div class="fixed inset-0 flex items-center justify-center bg-black/50">
  <div class="container">
    <div class="my-3 px-8 text-white">
      <a class="flex flex-row items-center space-x-1" href="/">
        <Home />
        <span>return home</span>
      </a>
    </div>
    <div
      class="rounded border-4 border-error bg-neutral p-8 text-neutral-content"
    >
      <h1 class="mb-2 text-5xl">{title || "An error occurred"}</h1>
      {#if subtitle || error}
        <h2 class="my-2 text-3xl">{subtitle || error?.message}</h2>
      {/if}
      {#if message}
        <span>{message}</span>
      {/if}
    </div>
  </div>
</div>
