// apps/web-tanstack-react/src/components/status/StatusBar.tsx
import type { FunctionComponent } from "react";
import styles from "client-css/m/status.module.scss";

const StatusBar: FunctionComponent<{ error?: boolean; fetching?: boolean }> = ({ fetching, error }) => {
  return (<div className={`${styles.bar}${fetching ? ` ${styles.busy}` : ""}${error ? ` ${styles.error}` : ""}`}></div>
  );
};

export default StatusBar;

// apps/web-svelte/src/lib/components/status/StatusBar.svelte
<script lang="ts">
  import styles from "client-css/m/status.module.scss";

  type Props = {
    error?: boolean;
    fetching?: boolean;
  };

  const {
    fetching,
    error,
  }: Props = $props();
</script>

<!-- eslint-disable-next-line @stylistic/quotes -->
<div class="{styles.bar}{fetching ? ` ${styles.busy}` : ""}{error ? ` ${styles.error}` : ""}"></div>
