// apps/web-tanstack-react/src/components/gallery/Gallery.tsx
import type { ImageSort } from "models";
import type { FunctionComponent } from "react";
import styles from "client-css/m/gallery.module.scss";
import { useEffect, useRef } from "react";
import { useImages } from "#/hooks/useImages";
import ErrorMessage from "../status/ErrorMessage";
import StatusBar from "../status/StatusBar";
import ImageCard from "./ImageCard";

const Gallery: FunctionComponent<{
  tags: readonly string[];
  sort: ImageSort;
}> = ({ tags, sort }) => {
  const result = useImages(tags, sort);

  const endDivRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const observer = new IntersectionObserver((entries) => {
      if (entries[0] && entries[0].isIntersecting) {
        result.fetchMore();
      }
    });

    if (endDivRef.current) {
      observer.observe(endDivRef.current);
    }

    return () => {
      observer.disconnect();
    };
  }, [result]);

  return (
    <>
      {result.images && (
        <>
          <div className={styles.gallery}>
            {result.images.map(image => (
              <ImageCard key={image.id} image={image} />
            ))}
          </div>
          <div className={styles.sentinel} ref={endDivRef}></div>
        </>
      )}

      {result.error
        && <ErrorMessage error={result.error} title={result.error.name}></ErrorMessage>}

      <StatusBar error={!!result.error} fetching={result.fetching}></StatusBar>
    </>
  );
};

export default Gallery;

// apps/web-nuxt/app/components/Gallery.vue
<script setup lang="ts">
import type { ImageSort } from "models";
import type { ComponentPublicInstance } from "#imports";
import styles from "client-css/m/gallery.module.scss";
import { useImages } from "#imports";

const props = defineProps<{
  tags: readonly string[];
  sort: ImageSort;
}>();

const {
  images,
  fetching,
  error,
  stale,
  fetchMore,
} = useImages(
  toRef(() => props.tags),
  toRef(() => props.sort),
);

const observer = ref<IntersectionObserver>();

const endRef = (node: ComponentPublicInstance | Element | null) => {
  if (observer.value) {
    observer.value.disconnect();
  }

  observer.value = new IntersectionObserver((entries) => {
    if (entries[0]?.isIntersecting) {
      fetchMore();
    }
  });

  if (node) {
    observer.value.observe(node as Element);
  }
};
</script>

<template>
  <div
    :class="styles.gallery"
  >
    <template
      v-for="image in images"
      :key="image.id"
    >
      <div>
        <ImageCard :image="image" />
      </div>
    </template>
  </div>
  <div :ref="endRef" :class="styles.sentinel" />

  <ErrorMessage
    v-if="error"
    :error="error"
    :title="error.name"
  />

  <StatusBar
    :error="!!error"
    :fetching="fetching || stale"
  />

  <ScrollButtons />
</template>
